In [1]:
import pandas as pd
import altair as alt
import os
import shutil

In [2]:
df = pd.read_csv('data/raw/data.csv')
df

,country_or_area,year,value,category
0,Australia,2014,393126.946994,carbon_dioxide_co2_emissions_without_land_use_...
1,Australia,2013,396913.936530,carbon_dioxide_co2_emissions_without_land_use_...
2,Australia,2012,406462.847704,carbon_dioxide_co2_emissions_without_land_use_...
3,Australia,2011,403705.528314,carbon_dioxide_co2_emissions_without_land_use_...
4,Australia,2010,406200.993184,carbon_dioxide_co2_emissions_without_land_use_...
...,...,...,...,...
8401,United States of America,1994,593.222570,unspecified_mix_of_hydrofluorocarbons_hfcs_and...
8402,United States of America,1993,586.939752,unspecified_mix_of_hydrofluorocarbons_hfcs_and...
8403,United States of America,1992,574.414624,unspecified_mix_of_hydrofluorocarbons_hfcs_and...
8404,United States of America,1991,566.900968,unspecified_mix_of_hydrofluorocarbons_hfcs_and...
8405,United States of America,1990,293.205663,unspecified_mix_of_hydrofluorocarbons_hfcs_and...

In [3]:
df['category'].unique()

<StringArray>
[ 'carbon_dioxide_co2_emissions_without_land_use_land_use_change_and_forestry_lulucf_in_kilotonne_co2_equivalent',
                'greenhouse_gas_ghgs_emissions_including_indirect_co2_without_lulucf_in_kilotonne_co2_equivalent',
 'greenhouse_gas_ghgs_emissions_without_land_use_land_use_change_and_forestry_lulucf_in_kilotonne_co2_equivalent',
                                                  'hydrofluorocarbons_hfcs_emissions_in_kilotonne_co2_equivalent',
         'methane_ch4_emissions_without_land_use_land_use_change_and_forestry_lulucf_in_kilotonne_co2_equivalent',
                                                 'nitrogen_trifluoride_nf3_emissions_in_kilotonne_co2_equivalent',
   'nitrous_oxide_n2o_emissions_without_land_use_land_use_change_and_forestry_lulucf_in_kilotonne_co2_equivalent',
                                                    'perfluorocarbons_pfcs_emissions_in_kilotonne_co2_equivalent',
                                                 'sulphur_hexafluoride_sf6_emissions_in_kilotonne_co2_equivalent',
     'unspecified_mix_of_hydrofluorocarbons_hfcs_and_perfluorocarbons_pfcs_emissions_in_kilotonne_co2_equivalent']
Length: 10, dtype: str

In [4]:
processed_values = {
  'carbon_dioxide_co2_emissions_without_land_use_land_use_change_and_forestry_lulucf_in_kilotonne_co2_equivalent': 'CO2 Emissions',
  'greenhouse_gas_ghgs_emissions_including_indirect_co2_without_lulucf_in_kilotonne_co2_equivalent': 'GHG Emissions with CO2',
  'greenhouse_gas_ghgs_emissions_without_land_use_land_use_change_and_forestry_lulucf_in_kilotonne_co2_equivalent': 'GHG Emissions',
  'hydrofluorocarbons_hfcs_emissions_in_kilotonne_co2_equivalent': 'HFC Emissions',
  'methane_ch4_emissions_without_land_use_land_use_change_and_forestry_lulucf_in_kilotonne_co2_equivalent': 'CH4 Emissions',
  'nitrogen_trifluoride_nf3_emissions_in_kilotonne_co2_equivalent': 'NF3 Emissions',
  'nitrous_oxide_n2o_emissions_without_land_use_land_use_change_and_forestry_lulucf_in_kilotonne_co2_equivalent': 'N2O Emissions',
  'perfluorocarbons_pfcs_emissions_in_kilotonne_co2_equivalent': 'PFC Emissions',
  'sulphur_hexafluoride_sf6_emissions_in_kilotonne_co2_equivalent': 'SF6 Emissions',
  'unspecified_mix_of_hydrofluorocarbons_hfcs_and_perfluorocarbons_pfcs_emissions_in_kilotonne_co2_equivalent': 'Unspecified Emissions'
}
df['emission'] = df['category'].map(processed_values)
df['units'] = 'Kilotonne CO2 Equivalent'
df = df.drop(columns=['category'])
df = df.rename(columns={'country_or_area': 'country'})

In [5]:
df.to_csv('data/processed/data.csv', index=False)

In [6]:
df.describe()

              year         value
count  8406.000000  8.406000e+03
mean   2002.188437  2.055472e+05
std       7.151605  8.041504e+05
min    1990.000000  1.103750e-06
25%    1996.000000  2.976980e+02
50%    2002.000000  7.840318e+03
75%    2008.000000  6.589885e+04
max    2014.000000  7.422208e+06

In [7]:
df.isna().sum()

country     0
year        0
value       0
emission    0
units       0
dtype: int64

In [8]:
df1 = df[(df['emission'] == 'CO2 Emissions') & (df['year'] == 1990)]

In [9]:
df1

,country,year,value,emission,units
24,Australia,1990,2.782659e+05,CO2 Emissions,Kilotonne CO2 Equivalent
49,Austria,1990,6.229717e+04,CO2 Emissions,Kilotonne CO2 Equivalent
74,Belarus,1990,1.004381e+05,CO2 Emissions,Kilotonne CO2 Equivalent
99,Belgium,1990,1.199825e+05,CO2 Emissions,Kilotonne CO2 Equivalent
124,Bulgaria,1990,7.819788e+04,CO2 Emissions,Kilotonne CO2 Equivalent
149,Canada,1990,4.634933e+05,CO2 Emissions,Kilotonne CO2 Equivalent
174,Croatia,1990,2.339008e+04,CO2 Emissions,Kilotonne CO2 Equivalent
199,Cyprus,1990,4.621007e+03,CO2 Emissions,Kilotonne CO2 Equivalent
224,Czech Republic,1990,1.616620e+05,CO2 Emissions,Kilotonne CO2 Equivalent
249,Denmark,1990,5.430643e+04,CO2 Emissions,Kilotonne CO2 Equivalent
274,Estonia,1990,3.666603e+04,CO2 Emissions,Kilotonne CO2 Equivalent
299,European Union,1990,4.462205e+06,CO2 Emissions,Kilotonne CO2 Equivalent
324,Finland,1990,5.695085e+04,CO2 Emissions,Kilotonne CO2 Equivalent
349,France,1990,4.006526e+05,CO2 Emissions,Kilotonne CO2 Equivalent
374,Germany,1990,1.052238e+06,CO2 Emissions,Kilotonne CO2 Equivalent
399,Greece,1990,8.340372e+04,CO2 Emissions,Kilotonne CO2 Equivalent
424,Hungary,1990,7.311520e+04,CO2 Emissions,Kilotonne CO2 Equivalent
449,Iceland,1990,2.106026e+03,CO2 Emissions,Kilotonne CO2 Equivalent
474,Ireland,1990,3.276853e+04,CO2 Emissions,Kilotonne CO2 Equivalent
499,Italy,1990,4.362042e+05,CO2 Emissions,Kilotonne CO2 Equivalent
524,Japan,1990,1.155994e+06,CO2 Emissions,Kilotonne CO2 Equivalent
549,Latvia,1990,1.979429e+04,CO2 Emissions,Kilotonne CO2 Equivalent
574,Liechtenstein,1990,1.987751e+02,CO2 Emissions,Kilotonne CO2 Equivalent
599,Lithuania,1990,3.581289e+04,CO2 Emissions,Kilotonne CO2 Equivalent
624,Luxembourg,1990,1.194401e+04,CO2 Emissions,Kilotonne CO2 Equivalent
649,Malta,1990,1.860474e+03,CO2 Emissions,Kilotonne CO2 Equivalent
673,Monaco,1990,9.538518e+01,CO2 Emissions,Kilotonne CO2 Equivalent
698,Netherlands,1990,1.624976e+05,CO2 Emissions,Kilotonne CO2 Equivalent
723,New Zealand,1990,2.541977e+04,CO2 Emissions,Kilotonne CO2 Equivalent
748,Norway,1990,3.569482e+04,CO2 Emissions,Kilotonne CO2 Equivalent
773,Poland,1990,3.787825e+05,CO2 Emissions,Kilotonne CO2 Equivalent
798,Portugal,1990,4.580907e+04,CO2 Emissions,Kilotonne CO2 Equivalent
823,Romania,1990,1.747319e+05,CO2 Emissions,Kilotonne CO2 Equivalent
848,Russian Federation,1990,2.589725e+06,CO2 Emissions,Kilotonne CO2 Equivalent
873,Slovakia,1990,6.183757e+04,CO2 Emissions,Kilotonne CO2 Equivalent
898,Slovenia,1990,1.508831e+04,CO2 Emissions,Kilotonne CO2 Equivalent
923,Spain,1990,2.301550e+05,CO2 Emissions,Kilotonne CO2 Equivalent
948,Sweden,1990,5.754654e+04,CO2 Emissions,Kilotonne CO2 Equivalent
973,Switzerland,1990,4.411553e+04,CO2 Emissions,Kilotonne CO2 Equivalent
998,Turkey,1990,1.467506e+05,CO2 Emissions,Kilotonne CO2 Equivalent
1023,Ukraine,1990,6.930248e+05,CO2 Emissions,Kilotonne CO2 Equivalent
1048,United Kingdom,1990,5.963985e+05,CO2 Emissions,Kilotonne CO2 Equivalent
1073,United States of America,1990,5.115095e+06,CO2 Emissions,Kilotonne CO2 Equivalent

In [10]:
df_total = df.groupby(['emission', 'year'])['value'].sum().reset_index()
df_total['units'] = 'Kilotonne CO2 Equivalent'

In [11]:
df_total

                  emission  year         value                     units
0            CH4 Emissions  1990  3.745046e+06  Kilotonne CO2 Equivalent
1            CH4 Emissions  1991  3.634010e+06  Kilotonne CO2 Equivalent
2            CH4 Emissions  1992  3.505710e+06  Kilotonne CO2 Equivalent
3            CH4 Emissions  1993  3.404186e+06  Kilotonne CO2 Equivalent
4            CH4 Emissions  1994  3.314308e+06  Kilotonne CO2 Equivalent
..                     ...   ...           ...                       ...
245  Unspecified Emissions  2010  8.494681e+03  Kilotonne CO2 Equivalent
246  Unspecified Emissions  2011  8.531825e+03  Kilotonne CO2 Equivalent
247  Unspecified Emissions  2012  8.948590e+03  Kilotonne CO2 Equivalent
248  Unspecified Emissions  2013  9.380616e+03  Kilotonne CO2 Equivalent
249  Unspecified Emissions  2014  9.753790e+03  Kilotonne CO2 Equivalent

[250 rows x 4 columns]

In [12]:
alt.Chart(df_total).mark_line().encode(
  x=alt.X("year:Q", bin=False, title="Year"),
  y=alt.Y("value:Q", title="Kilotonne CO2 Equivalent")
).facet(
  column=alt.Column("emission:N", title="Emission Type")
)

alt.FacetChart(...)

In [13]:
df_total.to_csv('data/processed/total_emissions.csv', index=False)

In [14]:
df_country = df.groupby(['country', 'year'])['value'].sum().reset_index()
df_country['units'] = 'Kilotonne CO2 Equivalent'
df_country = df_country[df_country['country'] != 'European Union']

In [15]:
df_country

                       country  year         value                     units
0                    Australia  1990  1.255869e+06  Kilotonne CO2 Equivalent
1                    Australia  1991  1.256022e+06  Kilotonne CO2 Equivalent
2                    Australia  1992  1.269240e+06  Kilotonne CO2 Equivalent
3                    Australia  1993  1.271295e+06  Kilotonne CO2 Equivalent
4                    Australia  1994  1.272279e+06  Kilotonne CO2 Equivalent
...                        ...   ...           ...                       ...
1069  United States of America  2010  2.095637e+07  Kilotonne CO2 Equivalent
1070  United States of America  2011  2.059619e+07  Kilotonne CO2 Equivalent
1071  United States of America  2012  1.992903e+07  Kilotonne CO2 Equivalent
1072  United States of America  2013  2.039994e+07  Kilotonne CO2 Equivalent
1073  United States of America  2014  2.061134e+07  Kilotonne CO2 Equivalent

[1049 rows x 4 columns]

In [16]:
alt.Chart(df_country).mark_line().encode(
  x=alt.X("year:Q", bin=False, title="Year"),
  y=alt.Y("value:Q", title="Kilotonne CO2 Equivalent")
).facet(
  column=alt.Column("country:N", title="Country")
)

alt.FacetChart(...)

In [17]:
df_country.to_csv('data/processed/country_emissions.csv', index=False)

In [18]:
# Copy files
files = os.listdir('data/processed')

end_dir = r'C:\Users\jairo\Documents\GitHub\VisualizacionDatos_FinalProject\frontend\public\data'
for file in files:
  shutil.copy(f'data/processed/{file}', f'{end_dir}/{file}')